services:
  my-node:
    build: ../BuildingWithDockerfile/node-example
    ports:
      - "3001:3000"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_PASS: mypass123
    ports:
      - 5672:5672
      - 15672:15672