services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass123
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data